services:
  # Next.js Application (Test)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - NODE_ENV=test
    container_name: zgobooking-app-test
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - env.docker.test
    depends_on:
      - db
      - redis
    networks:
      - zgobooking-network
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    command: npm test

  # PostgreSQL Database (Test)
  db:
    image: postgres:15-alpine
    container_name: zgobooking-postgres-test
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: AtlasPostgres_test
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres-data-test:/var/lib/postgresql/data
      - ./prisma/migrations:/docker-entrypoint-initdb.d
    networks:
      - zgobooking-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache (Test)
  redis:
    image: redis:7-alpine
    container_name: zgobooking-redis-test
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis-data-test:/data
    networks:
      - zgobooking-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres-data-test:
    driver: local
  redis-data-test:
    driver: local

networks:
  zgobooking-network:
    driver: bridge 