services:
  # Next.js Application (Simple)
  app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: zgobooking-app-simple
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - env.docker
    depends_on:
      - db
      - redis
    networks:
      - zgobooking-network
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: zgobooking-postgres-simple
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: AtlasPostgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres-data-simple:/var/lib/postgresql/data
    networks:
      - zgobooking-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: zgobooking-redis-simple
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data-simple:/data
    networks:
      - zgobooking-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres-data-simple:
    driver: local
  redis-data-simple:
    driver: local

networks:
  zgobooking-network:
    driver: bridge 